print (" ...     CALCUL D'UN PONT DIVISEUR DE TENSION    ... ")
print ("Valeur à calculer : ")
print ("1. Tension de sortie")
print ("2. Tension d'entrée")
print ("3. Résistance R1")
print ("4. Résistance R2")
choix_calcul = int(input("Choix : "))
if choix_calcul == 1:
    print("Calcul de la tension de sortie Vout")
    R1 = int(input("Valeur de la résistance R1 (en ohms) : "))
    R2 = int(input("Valeur de la résistance R2 (en ohms) : "))
    Vin = float(input("Tension d'entrée (en volts) : "))
    Vout = Vin * (R2 / (R1 + R2))
    print(f"Tension de sortie Vout = {Vout:.2f} V")
elif choix_calcul == 2:
    print("Calcul de la tension d'entrée Vin")
    R1 = int(input("Valeur de la résistance R1 (en ohms) : "))
    R2 = int(input("Valeur de la résistance R2 (en ohms) : "))
    Vout = float(input("Tension de sortie (en volts) : "))
    Vin = Vout * ((R1 + R2) / R2)
    print(f"Tension d'entrée Vin = {Vin:.2f} V")
elif choix_calcul == 3:
    print("Calcul de la résistance R1")
    R2 = int(input("Valeur de la résistance R2 (en ohms) : "))
    Vin = float(input("Tension d'entrée (en volts) : "))
    Vout = float(input("Tension de sortie (en volts) : "))
    R1 = (R2 * Vin / Vout) - R2
    print(f"Résistance R1 = {R1:.2f} ohms")
elif choix_calcul == 4:
    print("Calcul de la résistance R2")
    R1 = int(input("Valeur de la résistance R1 (en ohms) : "))
    Vin = float(input("Tension d'entrée (en volts) : "))
    Vout = float(input("Tension de sortie (en volts) : "))
    R2 = (Vout * R1 / (Vin - Vout))
    print(f"Résistance R2 = {R2:.2f} ohms")